Traceback (most recent call last):
  File "/home/lolasolovyeva/PycharmProjects/LLMGeneratedCodePowerConsumption/generated_code_files/o1/Find_the_Maximum_Sum_of_Node_Values/Find_the_Maximum_Sum_of_Node_Values_solution.py", line 114, in <module>
    testSolution(solution)
  File "/home/lolasolovyeva/PycharmProjects/LLMGeneratedCodePowerConsumption/generated_code_files/o1/Find_the_Maximum_Sum_of_Node_Values/Find_the_Maximum_Sum_of_Node_Values_solution.py", line 81, in testSolution
    assert solution.maximumValueSum(nums, k, edges) == expected_result, f"Test case 3 failed. Expected {expected_result}."
AssertionError: Test case 3 failed. Expected 24.

 Performance counter stats for 'system wide':

              0,77 Joules power/energy-pkg/                                                     

       0,051495104 seconds time elapsed

